name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: |
        git clone --depth 1 --quiet --single-branch https://github.com/vlang/v.git /tmp/v
        make -C /tmp/v
        /tmp/v/v doctor
        /tmp/v/v -cc tcc json2v -o json2v/json2v
    - name: test
      run: |
        ./test.sh